"use client";
// Every string the interface shows, in one place. A few dozen keys do not justify an i18n
// dependency, and keeping them together makes it easy to see the whole voice of the app.
import { useCallback } from "react";

export const STRINGS = {
  tagline: "Turn an audio file into a playable record you can print on an ordinary FDM printer. No 0.2 mm nozzle, no resin. A 0.4 mm nozzle and PLA.",
  safetyTitle: "Read this before you print",
  safetyBody: "A disc takes one to three hours to print. Stay near the printer, especially for the first layer. The record is soft PLA and it wears a stylus faster than vinyl does: play it with a cheap cartridge, never with an expensive one. You print and play at your own risk.",
  badgeNozzle: "0.4 mm nozzle · PLA",
  badgeRpm: "rpm",
  badgeBrowser: "runs entirely in your browser",
  step1: "Printer profile",
  step1Hint: "once, then it is remembered in your browser",
  step1Done: "ready",
  step1Drop: "Drop template.gcode.3mf here, or click to choose",
  step1How: "Where do I get this file",
  step1HowBody: "In your slicer, slice any small object (a 10 mm cube) with your own profile: your printer, your nozzle, PLA. Then export the sliced plate as a .gcode.3mf file. The engine only takes your printer's start and end G-code from it and writes everything in between. The repository ships ready made templates for the Bambu Lab P1S in templates/.",
  step1Change: "Change",
  step1Nozzle: "nozzle",
  step1Layer: "layer",
  step2: "What to press",
  step3: "Format",
  step3Hint: "the rest has values that were measured, not guessed",
  step4: "Cut the record",
  step5: "Tune it to your turntable",
  step5Hint: "optional, but it is the only way to better sound",
  modeMelody: "Test melody",
  modeMelodySub: "A continuous spiral playing a public domain tune. You need no files, so it makes a good first print.",
  modeMusic: "Your music",
  modeMusicSub: "Any audio or video file. You pick the passage, the engine does the rest.",
  modeCalib: "Tuning record",
  modeCalibSub: "Blocks of eight tones along the spiral. Play it, record it, and the engine learns your turntable.",
  modeRings: "Groove diagnostics",
  modeRingsSub: "Closed rings with different groove shapes. For tuning geometry, not for listening.",
  dropAudio: "Drop a music file (mp3, m4a, wav, mp4)",
  loaded: "Loaded",
  dropOther: "(drop another file to change it)",
  diameter: "Diameter",
  diameter250: "250 mm, a full 256 mm bed",
  diameter200: "200 mm, quicker",
  diameter170: "170 mm, shortest print",
  speed: "Speed",
  speedBrightest: "78, brightest",
  speedBalanced: "45, balanced",
  speedLongest: "33⅓, longest and darkest",
  hole: "Spindle hole (mm)",
  decor: "Centre pattern, independent of colours",
  twoColour: "Two colours",
  twoColourSub: "base in one, grooves and pattern in the other",
  labelText: "Text in the centre",
  labelTextSub: "engraved together with the pattern",
  line1: "First line",
  line2: "Second line",
  letterHeight: "Letter height (mm)",
  textNote: "Capitals, digits and punctuation. Letters are drawn with a single nozzle pass, so below 5 mm they start to merge. The pattern moves aside so it does not run into the text.",
  howColour: "How to change colour",
  pauseOption: "Pause, then you swap the spool yourself",
  amsOption: "AMS: switch to tray",
  generate: "Cut the record",
  generating: "Carving the groove…",
  decoding: "Decoding in your browser…",
  listening: "Listening to the recording…",
  needProfile: "Printer profile first (step 01).",
  needAudio: "Drop a music file in step 02.",
  withCalibration: "with your turntable's correction",
  fits: "fits",
  turns: "turns",
  band: "band Hz, edge→centre",
  thickness: "thickness",
  printTime: "print",
  filament: "filament",
  layers: "layers",
  file: "file",
  sound: "audio",
  grooveEnd: "groove ends",
  download: "Download",
  rawWarn: "Raw G-code. Without a printer profile it has no start or end.",
  previewNote: "Preview: the signal stored in the groove, after playback equalisation. It carries no print noise, so it shows the bandwidth, not the quality.",
  advanced: "Groove and sound, for the curious",
  amplitude: "Amplitude (mm)",
  grooveFloor: "Groove floor (mm)",
  wallLayers: "Wall layers",
  wallLayerOption: "{n}, {mm} mm trench",
  filter: "Top filter (Hz)",
  driveLabel: "Drive (dB)",
  presence: "Brightness (dB)",
  compression: "Compression (dB)",
  riaa: "RIAA pre-emphasis",
  spaghetti: "no spaghetti detector",
  useCalib: "apply turntable correction",
  calibIntro: "Print the tuning record (step 02), play it at the same speed and record it over USB. In Audacity start recording before you drop the needle. Upload the recording here. The engine measures how much of each of the eight tones reached the amplifier, separately at the rim and in the centre, and computes the correction every later record gets.",
  calibDrop: "Drop the recording of the tuning record (WAV / mp3)",
  calibFirst: "Generate a tuning record first. Its layout is what the recording is matched against.",
  calibRemove: "Remove profile",
  calibMade: "measured on",
  calibResult: "Pattern found {sec} s into the recording, {blocks} blocks, turntable running {pct}% off nominal.",
  calibFooter: "measured, then correction, in dB relative to the band median. Only what sits at least 6 dB above the noise is lifted, and never by more than 9 dB.",
  footPlay: "Playing.",
  footPlayBody: "tracking force 2.0 g, anti-skate 2. Lower the needle with the cueing lever onto the outer run-in.",
  footHonest: "Honestly.",
  footPrivacy: "Private.",
  footPrivacyBody: "Your file never leaves the browser. There is no server to upload it to.",
  source: "Source on GitHub",
  decorRings: "Rings", decorSpiral: "Spiral", decorSunburst: "Rays", decorStar: "Star",
  decorRosette: "Rosette", decorWaves: "Waves", decorGuilloche: "Guilloche", decorNone: "Plain",
  draftRestored: "Restored your previous session.",
  errDecode: "Could not decode that file. Try mp3, m4a, wav, or an mp4 with an audio track.",
  errDecodeRec: "Could not decode the recording. Export it from Audacity as WAV.",
  errTemplate: "Could not read that template.",
  startSec: "Passage starts at (s)",
  trackLen: "The track is {len} s, the record fits {cap} s. The wax will carry {from} to {to} s. Click the waveform to pick the chorus.",
  pauseNote: "The printer stops after the base, moves aside and waits. You swap the filament and resume on the screen. A pause shows one filament in the print dialog and a marker on the layer slider, because only one spool is loaded at a time.",
  amsNote: "AMS: the printer cuts the filament itself, loads the tray and purges the nozzle. The file declares two filaments, so the print dialog asks you to assign both.",
  grooveWarn: "The groove reaches {r} mm, so your tonearm may not track that far in.",
  thRadius: "radius", thTone: "tone", thFloor: "floor", thAmp: "amplitude", thLayers: "layers", thVariant: "variant", thNoise: "noise",
  tune: "Tune",
  howItWorks: "How it works",
  outputFormat: "Output",
  formatGcode: "G-code, ready to print",
  formatModel: "3MF model, you slice it",
  formatModelNote: "You get a solid you slice yourself, so nothing bypasses your own printer profile. The groove has to be wider for a slicer to render it, so a disc holds less music, and colours and the label are up to your slicer.",
  triangles: "triangles",
  errGeneric: "Something went wrong while building the file.",
  errReport: "If it keeps happening, open an issue on GitHub with the settings you used.",
  errDetails: "Technical details",
  phoneWarn: "On a phone the file is built in the browser and usually runs out of memory. Use a laptop or desktop.",
  tuneNote: "All of these are in the public domain and are synthesised here, so no recording rights are involved.",
} as const;

export type Key = keyof typeof STRINGS;

/** Looks a string up and fills {placeholders}. */
export function text(key: Key, vars?: Record<string, string | number>): string {
  const s: string = STRINGS[key];
  if (!vars) return s;
  return Object.entries(vars).reduce((acc, [k, v]) => acc.replaceAll(`{${k}}`, String(v)), s);
}

export function useText() {
  return useCallback(text, []);
}
